# Generated by Django 5.0.3 on 2024-04-12 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=3000),
            preserve_default=False,
        ),
    ]
